-- | This module is responsible for converting
-- IPA numbers to Unicode characters.
-- Unicode is a ubiquitous format for representing 
-- nearly all the characters and writing systems on Earth.
module IPANumberToUnicode exposing (..)

import IPAConstants.IPANumbers as Numbers
import IPAConstants.IPAUnicodeConstants exposing (..)


numberToUnicode : Int -> Char
numberToUnicode number =
    if number == Numbers.latin_small_letter_p then latin_small_letter_p
    else if number == Numbers.latin_small_letter_p then latin_small_letter_p
    else if number == Numbers.latin_small_letter_b then latin_small_letter_b
    else if number == Numbers.latin_small_letter_t then latin_small_letter_t
    else if number == Numbers.latin_small_letter_d then latin_small_letter_d
    else if number == Numbers.latin_small_letter_t_with_retroflex_hook then latin_small_letter_t_with_retroflex_hook
    else if number == Numbers.latin_small_letter_d_with_tail then latin_small_letter_d_with_tail
    else if number == Numbers.latin_small_letter_c then latin_small_letter_c
    else if number == Numbers.latin_small_letter_dotless_j_with_stroke then latin_small_letter_dotless_j_with_stroke
    else if number == Numbers.latin_small_letter_k then latin_small_letter_k
    else if number == Numbers.latin_small_letter_g then latin_small_letter_g
    else if number == Numbers.latin_small_letter_script_g then latin_small_letter_script_g
    else if number == Numbers.latin_small_letter_q then latin_small_letter_q
    else if number == Numbers.latin_letter_small_capital_g then latin_letter_small_capital_g
    else if number == Numbers.latin_letter_glottal_stop then latin_letter_glottal_stop
    else if number == Numbers.latin_small_letter_m then latin_small_letter_m
    else if number == Numbers.latin_small_letter_m_with_hook then latin_small_letter_m_with_hook
    else if number == Numbers.latin_small_letter_n then latin_small_letter_n
    else if number == Numbers.latin_small_letter_n_with_retroflex_hook then latin_small_letter_n_with_retroflex_hook
    else if number == Numbers.latin_small_letter_n_with_left_hook then latin_small_letter_n_with_left_hook
    else if number == Numbers.latin_small_letter_eng then latin_small_letter_eng
    else if number == Numbers.latin_letter_small_capital_n then latin_letter_small_capital_n
    else if number == Numbers.latin_letter_small_capital_b then latin_letter_small_capital_b
    else if number == Numbers.latin_small_letter_r then latin_small_letter_r
    else if number == Numbers.latin_letter_small_capital_r then latin_letter_small_capital_r
    else if number == Numbers.latin_small_letter_v_with_right_hook then latin_small_letter_v_with_right_hook
    else if number == Numbers.latin_small_letter_r_with_fishhook then latin_small_letter_r_with_fishhook
    else if number == Numbers.latin_small_letter_r_with_tail then latin_small_letter_r_with_tail
    else if number == Numbers.latin_small_letter_phi then latin_small_letter_phi
    else if number == Numbers.greek_small_letter_beta then greek_small_letter_beta
    else if number == Numbers.latin_small_letter_f then latin_small_letter_f
    else if number == Numbers.latin_small_letter_v then latin_small_letter_v
    else if number == Numbers.greek_small_letter_theta then greek_small_letter_theta
    else if number == Numbers.latin_small_letter_eth then latin_small_letter_eth
    else if number == Numbers.latin_small_letter_s then latin_small_letter_s
    else if number == Numbers.latin_small_letter_z then latin_small_letter_z
    else if number == Numbers.latin_small_letter_esh then latin_small_letter_esh
    else if number == Numbers.latin_small_letter_ezh then latin_small_letter_ezh
    else if number == Numbers.latin_small_letter_s_with_hook then latin_small_letter_s_with_hook
    else if number == Numbers.latin_small_letter_z_with_retroflex_hook then latin_small_letter_z_with_retroflex_hook
    else if number == Numbers.latin_small_letter_c_with_cedilla then latin_small_letter_c_with_cedilla
    else if number == Numbers.latin_small_letter_j_with_crossed_tail then latin_small_letter_j_with_crossed_tail
    else if number == Numbers.latin_small_letter_x then latin_small_letter_x
    else if number == Numbers.latin_small_letter_gamma then latin_small_letter_gamma
    else if number == Numbers.greek_small_letter_chi then greek_small_letter_chi
    else if number == Numbers.latin_letter_small_capital_inverted_r then latin_letter_small_capital_inverted_r
    else if number == Numbers.latin_small_letter_h_with_stroke then latin_small_letter_h_with_stroke
    else if number == Numbers.latin_letter_pharyngeal_voiced_fricative then latin_letter_pharyngeal_voiced_fricative
    else if number == Numbers.latin_small_letter_h then latin_small_letter_h
    else if number == Numbers.latin_small_letter_h_with_hook then latin_small_letter_h_with_hook
    else if number == Numbers.latin_small_letter_l_with_belt then latin_small_letter_l_with_belt
    else if number == Numbers.latin_small_letter_lezh then latin_small_letter_lezh
    else if number == Numbers.latin_small_letter_v_with_hook then latin_small_letter_v_with_hook
    else if number == Numbers.latin_small_letter_turned_r then latin_small_letter_turned_r
    else if number == Numbers.latin_small_letter_turned_r_with_hook then latin_small_letter_turned_r_with_hook
    else if number == Numbers.latin_small_letter_j then latin_small_letter_j
    else if number == Numbers.latin_small_letter_turned_m_with_long_leg then latin_small_letter_turned_m_with_long_leg
    else if number == Numbers.latin_small_letter_l then latin_small_letter_l
    else if number == Numbers.latin_small_letter_l_with_retroflex_hook then latin_small_letter_l_with_retroflex_hook
    else if number == Numbers.latin_small_letter_turned_y then latin_small_letter_turned_y
    else if number == Numbers.latin_letter_small_capital_l then latin_letter_small_capital_l
    else if number == Numbers.latin_letter_bilabial_click then latin_letter_bilabial_click
    else if number == Numbers.latin_letter_dental_click then latin_letter_dental_click
    else if number == Numbers.latin_letter_retroflex_click then latin_letter_retroflex_click
    else if number == Numbers.latin_letter_alveolar_click then latin_letter_alveolar_click
    else if number == Numbers.latin_letter_lateral_click then latin_letter_lateral_click
    else if number == Numbers.latin_small_letter_b_with_hook then latin_small_letter_b_with_hook
    else if number == Numbers.latin_small_letter_d_with_hook then latin_small_letter_d_with_hook
    else if number == Numbers.latin_small_letter_dotless_j_with_stroke_and_hook then latin_small_letter_dotless_j_with_stroke_and_hook
    else if number == Numbers.latin_small_letter_g_with_hook then latin_small_letter_g_with_hook
    else if number == Numbers.latin_letter_small_capital_g_with_hook then latin_letter_small_capital_g_with_hook
    else if number == Numbers.modifier_letter_apostrophe then modifier_letter_apostrophe
    else if number == Numbers.latin_small_letter_i then latin_small_letter_i
    else if number == Numbers.latin_small_letter_y then latin_small_letter_y
    else if number == Numbers.latin_small_letter_i_with_stroke then latin_small_letter_i_with_stroke
    else if number == Numbers.latin_small_letter_u_bar then latin_small_letter_u_bar
    else if number == Numbers.latin_small_letter_turned_m then latin_small_letter_turned_m
    else if number == Numbers.latin_small_letter_u then latin_small_letter_u
    else if number == Numbers.latin_letter_small_capital_i then latin_letter_small_capital_i
    else if number == Numbers.latin_letter_small_capital_y then latin_letter_small_capital_y
    else if number == Numbers.latin_small_letter_upsilon then latin_small_letter_upsilon
    else if number == Numbers.latin_small_letter_e then latin_small_letter_e
    else if number == Numbers.latin_small_letter_o_with_stroke then latin_small_letter_o_with_stroke
    else if number == Numbers.latin_small_letter_reversed_e then latin_small_letter_reversed_e
    else if number == Numbers.latin_small_letter_barred_o then latin_small_letter_barred_o
    else if number == Numbers.latin_small_letter_rams_horn then latin_small_letter_rams_horn
    else if number == Numbers.latin_small_letter_o then latin_small_letter_o
    else if number == Numbers.latin_small_letter_schwa then latin_small_letter_schwa
    else if number == Numbers.latin_small_letter_open_e then latin_small_letter_open_e
    else if number == Numbers.latin_small_ligature_oe then latin_small_ligature_oe
    else if number == Numbers.latin_small_letter_reversed_open_e then latin_small_letter_reversed_open_e
    else if number == Numbers.latin_small_letter_closed_reversed_open_e then latin_small_letter_closed_reversed_open_e
    else if number == Numbers.latin_small_letter_turned_v then latin_small_letter_turned_v
    else if number == Numbers.latin_small_letter_open_o then latin_small_letter_open_o
    else if number == Numbers.latin_small_letter_ae then latin_small_letter_ae
    else if number == Numbers.latin_small_letter_turned_a then latin_small_letter_turned_a
    else if number == Numbers.latin_small_letter_a then latin_small_letter_a
    else if number == Numbers.latin_letter_small_capital_oe then latin_letter_small_capital_oe
    else if number == Numbers.latin_small_letter_alpha then latin_small_letter_alpha
    else if number == Numbers.latin_small_letter_turned_alpha then latin_small_letter_turned_alpha
    else if number == Numbers.latin_small_letter_turned_w then latin_small_letter_turned_w
    else if number == Numbers.latin_small_letter_w then latin_small_letter_w
    else if number == Numbers.latin_small_letter_turned_h then latin_small_letter_turned_h
    else if number == Numbers.latin_letter_small_capital_h then latin_letter_small_capital_h
    else if number == Numbers.latin_letter_reversed_glottal_stop_with_stroke then latin_letter_reversed_glottal_stop_with_stroke
    else if number == Numbers.latin_letter_glottal_stop_with_stroke then latin_letter_glottal_stop_with_stroke
    else if number == Numbers.latin_small_letter_c_with_curl then latin_small_letter_c_with_curl
    else if number == Numbers.latin_small_letter_z_with_curl then latin_small_letter_z_with_curl
    else if number == Numbers.latin_small_letter_turned_r_with_long_leg then latin_small_letter_turned_r_with_long_leg
    else if number == Numbers.latin_small_letter_heng_with_hook then latin_small_letter_heng_with_hook
    else if number == Numbers.combining_double_inverted_breve then combining_double_inverted_breve
    else if number == Numbers.combining_double_breve_below then combining_double_breve_below
    else if number == Numbers.modifier_letter_vertical_line then modifier_letter_vertical_line
    else if number == Numbers.modifier_letter_low_vertical_line then modifier_letter_low_vertical_line
    else if number == Numbers.modifier_letter_triangular_colon then modifier_letter_triangular_colon
    else if number == Numbers.modifier_letter_half_triangular_colon then modifier_letter_half_triangular_colon
    else if number == Numbers.combining_breve then combining_breve
    else if number == Numbers.vertical_line then vertical_line
    else if number == Numbers.double_vertical_line then double_vertical_line
    else if number == Numbers.full_stop then full_stop
    else if number == Numbers.undertie then undertie
    else if number == Numbers.combining_ring_below then combining_ring_below
    else if number == Numbers.combining_caron_below then combining_caron_below
    else if number == Numbers.modifier_letter_small_h then modifier_letter_small_h
    else if number == Numbers.combining_right_half_ring_below then combining_right_half_ring_below
    else if number == Numbers.combining_left_half_ring_below then combining_left_half_ring_below
    else if number == Numbers.combining_plus_sign_below then combining_plus_sign_below
    else if number == Numbers.combining_minus_sign_below then combining_minus_sign_below
    else if number == Numbers.combining_diaeresis then combining_diaeresis
    else if number == Numbers.combining_x_above then combining_x_above
    else if number == Numbers.combining_vertical_line_below then combining_vertical_line_below
    else if number == Numbers.combining_inverted_breve_below then combining_inverted_breve_below
    else if number == Numbers.modifier_letter_rhotic_hook then modifier_letter_rhotic_hook
    else if number == Numbers.combining_diaeresis_below then combining_diaeresis_below
    else if number == Numbers.combining_tilde_below then combining_tilde_below
    else if number == Numbers.combining_seagul_below then combining_seagul_below
    else if number == Numbers.modifier_letter_small_w then modifier_letter_small_w
    else if number == Numbers.modifier_letter_small_j then modifier_letter_small_j
    else if number == Numbers.modifier_letter_small_gamma then modifier_letter_small_gamma
    else if number == Numbers.modifier_letter_small_reversed_glottal_stop then modifier_letter_small_reversed_glottal_stop
    else if number == Numbers.combining_tilde_overlay then combining_tilde_overlay
    else if number == Numbers.combining_up_tack_below then combining_up_tack_below
    else if number == Numbers.combining_down_tack_below then combining_down_tack_below
    else if number == Numbers.combining_left_tack_below then combining_left_tack_below
    else if number == Numbers.combining_right_tack_below then combining_right_tack_below
    else if number == Numbers.combining_bridge_below then combining_bridge_below
    else if number == Numbers.combining_inverted_bridge_below then combining_inverted_bridge_below
    else if number == Numbers.combining_square_below then combining_square_below
    else if number == Numbers.combining_tilde then combining_tilde
    else if number == Numbers.superscript_latin_small_letter_n then superscript_latin_small_letter_n
    else if number == Numbers.modifier_letter_small_l then modifier_letter_small_l
    else if number == Numbers.combining_left_angle_above then combining_left_angle_above
    else if number == Numbers.combining_double_acute_accent then combining_double_acute_accent
    else if number == Numbers.combining_acute_accent then combining_acute_accent
    else if number == Numbers.combining_macron then combining_macron
    else if number == Numbers.combining_grave_accent then combining_grave_accent
    else if number == Numbers.combining_double_grave_accent then combining_double_grave_accent
    else if number == Numbers.combining_caron then combining_caron
    else if number == Numbers.combining_circumflex_accent then combining_circumflex_accent
    else if number == Numbers.combining_macron_acute then combining_macron_acute
    else if number == Numbers.combining_grave_macron then combining_grave_macron
    else if number == Numbers.combining_grave_acute_grave then combining_grave_acute_grave
    else if number == Numbers.north_east_arrow then north_east_arrow
    else if number == Numbers.south_east_arrow then south_east_arrow
    else if number == Numbers.downwards_arrow then downwards_arrow
    else if number == Numbers.upwards_arrow then upwards_arrow
    else if number == Numbers.modifier_letter_extra_high_tone_bar then modifier_letter_extra_high_tone_bar
    else if number == Numbers.modifier_letter_high_tone_bar then modifier_letter_high_tone_bar
    else if number == Numbers.modifier_letter_mid_tone_bar then modifier_letter_mid_tone_bar
    else if number == Numbers.modifier_letter_low_tone_bar then modifier_letter_low_tone_bar
    else if number == Numbers.modifier_letter_extra_low_tone_bar then modifier_letter_extra_low_tone_bar
    else '∅' -- not recognized
