-- | This module is responsible for
-- converting Unicode characters that are IPA sympbols
-- into IPA numbers.
module UnicodeToIPANumber exposing (..)

import IPAConstants.IPANumbers as Numbers
import IPAConstants.IPAUnicodeConstants exposing (..)


unicodeToNumber : Char -> Int
unicodeToNumber character =
    if character == latin_small_letter_p then Numbers.latin_small_letter_p
    else if character == latin_small_letter_b then Numbers.latin_small_letter_b
    else if character == latin_small_letter_t then Numbers.latin_small_letter_t
    else if character == latin_small_letter_d then Numbers.latin_small_letter_d
    else if character == latin_small_letter_t_with_retroflex_hook then Numbers.latin_small_letter_t_with_retroflex_hook
    else if character == latin_small_letter_d_with_tail then Numbers.latin_small_letter_d_with_tail
    else if character == latin_small_letter_c then Numbers.latin_small_letter_c
    else if character == latin_small_letter_dotless_j_with_stroke then Numbers.latin_small_letter_dotless_j_with_stroke
    else if character == latin_small_letter_k then Numbers.latin_small_letter_k
    else if character == latin_small_letter_g then Numbers.latin_small_letter_g
    else if character == latin_small_letter_script_g then Numbers.latin_small_letter_script_g
    else if character == latin_small_letter_q then Numbers.latin_small_letter_q
    else if character == latin_letter_small_capital_g then Numbers.latin_letter_small_capital_g
    else if character == latin_letter_glottal_stop then Numbers.latin_letter_glottal_stop
    else if character == latin_small_letter_m then Numbers.latin_small_letter_m
    else if character == latin_small_letter_m_with_hook then Numbers.latin_small_letter_m_with_hook
    else if character == latin_small_letter_n then Numbers.latin_small_letter_n
    else if character == latin_small_letter_n_with_retroflex_hook then Numbers.latin_small_letter_n_with_retroflex_hook
    else if character == latin_small_letter_n_with_left_hook then Numbers.latin_small_letter_n_with_left_hook
    else if character == latin_small_letter_eng then Numbers.latin_small_letter_eng
    else if character == latin_letter_small_capital_n then Numbers.latin_letter_small_capital_n
    else if character == latin_letter_small_capital_b then Numbers.latin_letter_small_capital_b
    else if character == latin_small_letter_r then Numbers.latin_small_letter_r
    else if character == latin_letter_small_capital_r then Numbers.latin_letter_small_capital_r
    else if character == latin_small_letter_v_with_right_hook then Numbers.latin_small_letter_v_with_right_hook
    else if character == latin_small_letter_r_with_fishhook then Numbers.latin_small_letter_r_with_fishhook
    else if character == latin_small_letter_r_with_tail then Numbers.latin_small_letter_r_with_tail
    else if character == latin_small_letter_phi then Numbers.latin_small_letter_phi
    else if character == greek_small_letter_beta then Numbers.greek_small_letter_beta
    else if character == latin_small_letter_f then Numbers.latin_small_letter_f
    else if character == latin_small_letter_v then Numbers.latin_small_letter_v
    else if character == greek_small_letter_theta then Numbers.greek_small_letter_theta
    else if character == latin_small_letter_eth then Numbers.latin_small_letter_eth
    else if character == latin_small_letter_s then Numbers.latin_small_letter_s
    else if character == latin_small_letter_z then Numbers.latin_small_letter_z
    else if character == latin_small_letter_esh then Numbers.latin_small_letter_esh
    else if character == latin_small_letter_ezh then Numbers.latin_small_letter_ezh
    else if character == latin_small_letter_s_with_hook then Numbers.latin_small_letter_s_with_hook
    else if character == latin_small_letter_z_with_retroflex_hook then Numbers.latin_small_letter_z_with_retroflex_hook
    else if character == latin_small_letter_c_with_cedilla then Numbers.latin_small_letter_c_with_cedilla
    else if character == latin_small_letter_j_with_crossed_tail then Numbers.latin_small_letter_j_with_crossed_tail
    else if character == latin_small_letter_x then Numbers.latin_small_letter_x
    else if character == latin_small_letter_gamma then Numbers.latin_small_letter_gamma
    else if character == greek_small_letter_chi then Numbers.greek_small_letter_chi
    else if character == latin_letter_small_capital_inverted_r then Numbers.latin_letter_small_capital_inverted_r
    else if character == latin_small_letter_h_with_stroke then Numbers.latin_small_letter_h_with_stroke
    else if character == latin_letter_pharyngeal_voiced_fricative then Numbers.latin_letter_pharyngeal_voiced_fricative
    else if character == latin_small_letter_h then Numbers.latin_small_letter_h
    else if character == latin_small_letter_h_with_hook then Numbers.latin_small_letter_h_with_hook
    else if character == latin_small_letter_l_with_belt then Numbers.latin_small_letter_l_with_belt
    else if character == latin_small_letter_lezh then Numbers.latin_small_letter_lezh
    else if character == latin_small_letter_v_with_hook then Numbers.latin_small_letter_v_with_hook
    else if character == latin_small_letter_turned_r then Numbers.latin_small_letter_turned_r
    else if character == latin_small_letter_turned_r_with_hook then Numbers.latin_small_letter_turned_r_with_hook
    else if character == latin_small_letter_j then Numbers.latin_small_letter_j
    else if character == latin_small_letter_turned_m_with_long_leg then Numbers.latin_small_letter_turned_m_with_long_leg
    else if character == latin_small_letter_l then Numbers.latin_small_letter_l
    else if character == latin_small_letter_l_with_retroflex_hook then Numbers.latin_small_letter_l_with_retroflex_hook
    else if character == latin_small_letter_turned_y then Numbers.latin_small_letter_turned_y
    else if character == latin_letter_small_capital_l then Numbers.latin_letter_small_capital_l
    else if character == latin_letter_bilabial_click then Numbers.latin_letter_bilabial_click
    else if character == latin_letter_dental_click then Numbers.latin_letter_dental_click
    else if character == latin_letter_retroflex_click then Numbers.latin_letter_retroflex_click
    else if character == latin_letter_alveolar_click then Numbers.latin_letter_alveolar_click
    else if character == latin_letter_lateral_click then Numbers.latin_letter_lateral_click
    else if character == latin_small_letter_b_with_hook then Numbers.latin_small_letter_b_with_hook
    else if character == latin_small_letter_d_with_hook then Numbers.latin_small_letter_d_with_hook
    else if character == latin_small_letter_dotless_j_with_stroke_and_hook then Numbers.latin_small_letter_dotless_j_with_stroke_and_hook
    else if character == latin_small_letter_g_with_hook then Numbers.latin_small_letter_g_with_hook
    else if character == latin_letter_small_capital_g_with_hook then Numbers.latin_letter_small_capital_g_with_hook
    else if character == modifier_letter_apostrophe then Numbers.modifier_letter_apostrophe
    else if character == latin_small_letter_i then Numbers.latin_small_letter_i
    else if character == latin_small_letter_y then Numbers.latin_small_letter_y
    else if character == latin_small_letter_i_with_stroke then Numbers.latin_small_letter_i_with_stroke
    else if character == latin_small_letter_u_bar then Numbers.latin_small_letter_u_bar
    else if character == latin_small_letter_turned_m then Numbers.latin_small_letter_turned_m
    else if character == latin_small_letter_u then Numbers.latin_small_letter_u
    else if character == latin_letter_small_capital_i then Numbers.latin_letter_small_capital_i
    else if character == latin_letter_small_capital_y then Numbers.latin_letter_small_capital_y
    else if character == latin_small_letter_upsilon then Numbers.latin_small_letter_upsilon
    else if character == latin_small_letter_e then Numbers.latin_small_letter_e
    else if character == latin_small_letter_o_with_stroke then Numbers.latin_small_letter_o_with_stroke
    else if character == latin_small_letter_reversed_e then Numbers.latin_small_letter_reversed_e
    else if character == latin_small_letter_barred_o then Numbers.latin_small_letter_barred_o
    else if character == latin_small_letter_rams_horn then Numbers.latin_small_letter_rams_horn
    else if character == latin_small_letter_o then Numbers.latin_small_letter_o
    else if character == latin_small_letter_schwa then Numbers.latin_small_letter_schwa
    else if character == latin_small_letter_open_e then Numbers.latin_small_letter_open_e
    else if character == latin_small_ligature_oe then Numbers.latin_small_ligature_oe
    else if character == latin_small_letter_reversed_open_e then Numbers.latin_small_letter_reversed_open_e
    else if character == latin_small_letter_closed_reversed_open_e then Numbers.latin_small_letter_closed_reversed_open_e
    else if character == latin_small_letter_turned_v then Numbers.latin_small_letter_turned_v
    else if character == latin_small_letter_open_o then Numbers.latin_small_letter_open_o
    else if character == latin_small_letter_ae then Numbers.latin_small_letter_ae
    else if character == latin_small_letter_turned_a then Numbers.latin_small_letter_turned_a
    else if character == latin_small_letter_a then Numbers.latin_small_letter_a
    else if character == latin_letter_small_capital_oe then Numbers.latin_letter_small_capital_oe
    else if character == latin_small_letter_alpha then Numbers.latin_small_letter_alpha
    else if character == latin_small_letter_turned_alpha then Numbers.latin_small_letter_turned_alpha
    else if character == latin_small_letter_turned_w then Numbers.latin_small_letter_turned_w
    else if character == latin_small_letter_w then Numbers.latin_small_letter_w
    else if character == latin_small_letter_turned_h then Numbers.latin_small_letter_turned_h
    else if character == latin_letter_small_capital_h then Numbers.latin_letter_small_capital_h
    else if character == latin_letter_reversed_glottal_stop_with_stroke then Numbers.latin_letter_reversed_glottal_stop_with_stroke
    else if character == latin_letter_glottal_stop_with_stroke then Numbers.latin_letter_glottal_stop_with_stroke
    else if character == latin_small_letter_c_with_curl then Numbers.latin_small_letter_c_with_curl
    else if character == latin_small_letter_z_with_curl then Numbers.latin_small_letter_z_with_curl
    else if character == latin_small_letter_turned_r_with_long_leg then Numbers.latin_small_letter_turned_r_with_long_leg
    else if character == latin_small_letter_heng_with_hook then Numbers.latin_small_letter_heng_with_hook
    else if character == combining_double_inverted_breve then Numbers.combining_double_inverted_breve
    else if character == combining_double_breve_below then Numbers.combining_double_breve_below
    else if character == modifier_letter_vertical_line then Numbers.modifier_letter_vertical_line
    else if character == modifier_letter_low_vertical_line then Numbers.modifier_letter_low_vertical_line
    else if character == modifier_letter_triangular_colon then Numbers.modifier_letter_triangular_colon
    else if character == modifier_letter_half_triangular_colon then Numbers.modifier_letter_half_triangular_colon
    else if character == combining_breve then Numbers.combining_breve
    else if character == vertical_line then Numbers.vertical_line
    else if character == double_vertical_line then Numbers.double_vertical_line
    else if character == full_stop then Numbers.full_stop
    else if character == undertie then Numbers.undertie
    else if character == combining_ring_below then Numbers.combining_ring_below
    else if character == combining_ring_above then Numbers.combining_ring_above
    else if character == combining_caron_below then Numbers.combining_caron_below
    else if character == modifier_letter_small_h then Numbers.modifier_letter_small_h
    else if character == combining_right_half_ring_below then Numbers.combining_right_half_ring_below
    else if character == combining_left_half_ring_below then Numbers.combining_left_half_ring_below
    else if character == combining_plus_sign_below then Numbers.combining_plus_sign_below
    else if character == combining_minus_sign_below then Numbers.combining_minus_sign_below
    else if character == combining_diaeresis then Numbers.combining_diaeresis
    else if character == combining_x_above then Numbers.combining_x_above
    else if character == combining_vertical_line_above then Numbers.combining_vertical_line_above
    else if character == combining_vertical_line_below then Numbers.combining_vertical_line_below
    else if character == combining_inverted_breve_below then Numbers.combining_inverted_breve_below
    else if character == modifier_letter_rhotic_hook then Numbers.modifier_letter_rhotic_hook
    else if character == combining_diaeresis_below then Numbers.combining_diaeresis_below
    else if character == combining_tilde_below then Numbers.combining_tilde_below
    else if character == combining_seagul_below then Numbers.combining_seagul_below
    else if character == modifier_letter_small_w then Numbers.modifier_letter_small_w
    else if character == modifier_letter_small_j then Numbers.modifier_letter_small_j
    else if character == modifier_letter_small_gamma then Numbers.modifier_letter_small_gamma
    else if character == modifier_letter_small_reversed_glottal_stop then Numbers.modifier_letter_small_reversed_glottal_stop
    else if character == combining_tilde_overlay then Numbers.combining_tilde_overlay
    else if character == combining_up_tack_below then Numbers.combining_up_tack_below
    else if character == combining_down_tack_below then Numbers.combining_down_tack_below
    else if character == combining_left_tack_below then Numbers.combining_left_tack_below
    else if character == combining_right_tack_below then Numbers.combining_right_tack_below
    else if character == combining_bridge_below then Numbers.combining_bridge_below
    else if character == combining_inverted_bridge_below then Numbers.combining_inverted_bridge_below
    else if character == combining_square_below then Numbers.combining_square_below
    else if character == combining_tilde then Numbers.combining_tilde
    else if character == superscript_latin_small_letter_n then Numbers.superscript_latin_small_letter_n
    else if character == modifier_letter_small_l then Numbers.modifier_letter_small_l
    else if character == combining_left_angle_above then Numbers.combining_left_angle_above
    else if character == combining_double_acute_accent then Numbers.combining_double_acute_accent
    else if character == combining_acute_accent then Numbers.combining_acute_accent
    else if character == combining_macron then Numbers.combining_macron
    else if character == combining_grave_accent then Numbers.combining_grave_accent
    else if character == combining_double_grave_accent then Numbers.combining_double_grave_accent
    else if character == combining_caron then Numbers.combining_caron
    else if character == combining_circumflex_accent then Numbers.combining_circumflex_accent
    else if character == combining_macron_acute then Numbers.combining_macron_acute
    else if character == combining_grave_macron then Numbers.combining_grave_macron
    else if character == combining_grave_acute_grave then Numbers.combining_grave_acute_grave
    else if character == north_east_arrow then Numbers.north_east_arrow
    else if character == south_east_arrow then Numbers.south_east_arrow
    else if character == downwards_arrow then Numbers.downwards_arrow
    else if character == upwards_arrow then Numbers.upwards_arrow
    else if character == modifier_letter_extra_high_tone_bar then Numbers.modifier_letter_extra_high_tone_bar
    else if character == modifier_letter_high_tone_bar then Numbers.modifier_letter_high_tone_bar
    else if character == modifier_letter_mid_tone_bar then Numbers.modifier_letter_mid_tone_bar
    else if character == modifier_letter_low_tone_bar then Numbers.modifier_letter_low_tone_bar
    else if character == modifier_letter_extra_low_tone_bar then Numbers.modifier_letter_extra_low_tone_bar
    else 0 -- not recognized
